const ReadyState = {
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  STOP: 'STOP'
};

const Disposition = {
  VM_OR_NA_UNKNOWN: 'VM_OR_NA_UNKNOWN',
  WRONG_OR_DISCONNECTED: 'WRONG_OR_DISCONNECTED',
  CURRENT_CLIENT: 'CURRENT_CLIENT',
  VM_SAME_NAME_UNCONFIRMED: 'VM_SAME_NAME_UNCONFIRMED',
  CORRECT_NUMBER: 'CORRECT_NUMBER',
  NO_ANSWER: 'NO_ANSWER'
};

const PhoneStatus = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  CORRECT: 'CORRECT',
  WRONG: 'WRONG',
  VOICEMAIL: 'VOICEMAIL',
  NO_ANSWER: 'NO_ANSWER',
  SKIPPED: 'SKIPPED',
  EXHAUSTED: 'EXHAUSTED'
};

const SkipReason = {
  SIBLING_CORRECT: 'SIBLING_CORRECT',
  MAX_ATTEMPTS: 'MAX_ATTEMPTS',
  OUTSIDE_WINDOW: 'OUTSIDE_WINDOW',
  RETRY_PENDING: 'RETRY_PENDING',
  MANUAL_SKIP: 'MANUAL_SKIP'
};

module.exports = {
  ReadyState,
  Disposition,
  PhoneStatus,
  SkipReason
};